### ISSUE TITLE
Comma missing in "The Strength of God"

### ISSUE THREAD

**Issue by jpnance** [standardebooks/sherwood-anderson_winesburg-ohio#1]
https://github.com/standardebooks/sherwood-anderson_winesburg-ohio/blob/b9c24e0a44176686172a858275208b3ca9c80ff8/src/epub/text/the-strength-of-god.xhtml#L16

The excerpt "...good although somewhat worldly women..." should be amended with a comma thus: "...good, although somewhat worldly women..." The sentence doesn't make a ton of sense without that comma and, to be sure, the amended form is what appears in this scan of the book on page 174: https://archive.org/details/in.ernet.dli.2015.85326/page/n195/mode/2up

This error also shows up in the Gutenberg text so I'll submit the errata over to them as well.

**Comment by acabal** [comment]
Thanks, this should be fixed now!
