### ISSUE TITLE
Extra comma in "Death" should be deleted

### ISSUE THREAD

**Issue by jpnance** [standardebooks/sherwood-anderson_winesburg-ohio#2]
https://github.com/standardebooks/sherwood-anderson_winesburg-ohio/blob/56b63d6ababfb4a1e37eca128284ba6fc7f6dcd7/src/epub/text/death.xhtml#L39

The sentence "For a moment he sat staring at, the floor and then jumping up went for a walk." should be amended to "For a moment he sat staring at the floor and then jumping up went for a walk." (the same thing but without a comma). The comma is absent both in a hard copy of the book that I have and in this scan on page 280: https://archive.org/details/in.ernet.dli.2015.85326/page/n301/mode/2up

The error also shows up in the original Gutenberg text so I'll send the errata over to them as well.

**Comment by acabal** [comment]
Thanks, this should be fixed now!
